name: Publish

on:
  release:
    types:
      - published

jobs:
  release:
    name: Create & Publish Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

       # get part of the tag after the `v`
      - name: Extract tag version number
        id: get_version
        uses: battila7/get-version-action@v2
      
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - run: echo "Substitute the Manifest and Download URLs in the module.json"
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: 'module.json'
        env:
          version: ${{steps.get_version.outputs.version-without-v}}
          url: https://github.com/${{github.repository}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip
      
      - name: Package
        run: |
          zip -r vereteno.zip fonts lang templates dist/vereteno.js dist/vereteno.css system.json template.json README.md LICENSE
      - name: Update Release with Artifacts
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
          artifacts: './module.json, ./vereteno.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
